sudo: false

language: node_js

node_js:
  - '6'

branches:
  only:
    - master

cache:
  directories:
    - node_modules

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

install:
  - npm config set spin false
  - npm config set loglevel http
  - npm install

script:
  - npm test

addons:
  sauce_connect: true

env:
  global:
    - SAUCE_USERNAME=faejs
    - secure: "ZsvHzpG2Fn1PB08mSXTXr+Z5K3UszmlPzBJ1F0YkdFKvMLhPfjaEgWkFVELSHWPcM277HHCHjUXuKBGTVOBCdBPQly2oqmXEBXOqtkdR2BMIIPlW2m6GE8iIEPR1Sm8t/uxWQp//nBwhX5rW6RRByHJm9mzoXg9dGSeqM1+ZEKIh7kNWd5kmAy8xNd0dcP7wsGmm+5nxpmTrbQf+IXCKxVl5twJ9k+F+uUTMsotaybpcmyFbkYURG7lhEuRJKUJwnnjYRGvpklKFGUhbqG3A3LyrnnJOIK+awAnVnRUL21HssC+NW7/NSkOtGmWZUhzyJ4z92EPAIvtWp1JGJGpIF6D7sE0b/yd5n+xIX9U1pRbEYZM6BhPXdJMdUvK2O+v7kfMpUWrtaN56jhFk3plgINy+iGStw5151O8XPb3bwnT3WCNJkP7lxUGHgOaxJ9modzLEw6A6gNO84JpN/ATyLVMqLBI50oNmNj+13+gy0mOxBACBL8hZCUpqMJMUTY6bKO/QxUmS9kLdi5EztkPwWoUplrG0jZ9nen5rXke6zT1nSFj5bzxMmU7pFe29XSoFo0nCvzZvD1rGEmIspe2DU+FpT71zr3qc5tppvxBEYaTbJpgbsfKyMV+kHG1Y+dyvqkjuCTmaC7v7+mIP0rMyiII1rblCBgA0m/JmipWekoc="
